services:
  postgres:
    image: postgres:16
    container_name: wex-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wex_purchase_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wex-network

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: publish-with-ui
    image: wex-purchase-api:latest
    container_name: wex-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__PurchaseDb: "Host=postgres;Port=5432;Database=wex_purchase_db;Username=postgres;Password=postgres;"
      ApiAuthentication__ApiKey: "secret"
      RateLimiting__MaxRequestsPerWindow: "60"
      RateLimiting__WindowSizeInSeconds: "60"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wex-network

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile.UI
    image: wex-purchase-ui:latest
    container_name: wex-ui
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ApiAuthentication__ApiKey: "secret"
    ports:
      - "8085:8080"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wex-network

  seq:
    image: datalust/seq:latest
    container_name: seq_dashboard
    restart: unless-stopped
    ports:
      - "8081:80"      # Web UI Dashboard (Accessible at http://localhost:8081)
      - "5341:5341"    # Ingestion Port for logs
    environment:
      - ACCEPT_EULA=Y  # Mandatory to accept the Seq license agreement
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    volumes:
      - seq_data:/data
    networks:
      - wex-network

networks:
  wex-network:
    driver: bridge

volumes:
  postgres_data:
  seq_data:
