<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.0" />
	<PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Wex.Purchase.BusinessModels\Wex.Purchase.BusinessModels.csproj" />
  </ItemGroup>
</Project>